#!/usr/bin/env bash

set -euo pipefail

for x in bin build; do
    if [ ! -d "$WD/$x" ]; then
        mkdir "$WD/$x"
    fi
done

for x in "$WD/src/"*.hs; do
    (
        echo "$x"
        hlint "$x"
        ormolu -m inplace "$x"
    ) &
done

for _ in $(jobs -p); do
    wait -n
done

(
    flags=(
        "-fdiagnostics-color=always"
        -fprof-auto-top
        -funbox-strict-fields
        "-i$WD/src"
        "-optl -fuse-ld=lld"
        "-outputdir $WD/build"
        -prof
        -Wall
        -Wcompat
        -Werror
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        "-with-rtsopts -pa"
        -Wmonomorphism-restriction
        -Wpartial-fields
        -Wredundant-constraints
        -Wunused-packages
        -Wunused-type-patterns
    )
    files=(
        "$WD/data/02.txt"
        "$WD/data/05.txt"
        "$WD/data/07.txt"
        "$WD/data/09.txt"
    )
    ghc "${flags[@]}" -o "$WD/bin/main" "$WD/src/Main.hs"
    time "$WD/bin/main" "${files[@]}"
)
